<a href="https://colab.research.google.com/github/aryas-droid/Assessment-NumPyandPandas-Arya/blob/main/AssessmentA-Arya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#SECTION A – EASY

Q1. NumPy Array Creation – 2 Marks
Create a NumPy array containing the following values:
10, 20, 30, 40, 50
Display:
The array
Shape of the array
Data type of the array

In [ ]:
import numpy as np
num1=np.array([10,20,30,40,50])
print(num1)
# shape
print("Shape: ",num1.shape)
print("Datatypes: ",num1.dtype)

[10 20 30 40 50]
Shape:  (5,)
Datatypes:  int64

Q2 :Given: import numpy as np arr = np.array([5, 10, 15, 20, 25]) Using NumPy: Add 5 to every element.
Mutiply every element by 2.
Display the results

In [ ]:
#Given: import numpy as np arr = np.array([5, 10, 15, 20, 25]) Using NumPy: Add 5 to every element.
#Multiply every element by 2.
#Display the results

import numpy as np
arr = np.array([5, 10, 15, 20, 25])
print("Original array: ",arr)
print("After adding 5 : ",arr+5)
print("After multiplying by 2: ",arr*2)

Original array:  [ 5 10 15 20 25]
After adding 5 :  [10 15 20 25 30]
After multiplying by 2:  [10 20 30 40 50]

Q3. NumPy Statistical Operations

In [ ]:
#Given:
#arr = np.array([12, 15, 18, 20, 25, 30])
#Using NumPy, calculate:
#Mean
#Median
#Minimum
#Maximum
#Standard deviation

arr = np.array([12, 15, 18, 20, 25, 30])
print("Mean: ",arr.mean())
print("Minimum: ",arr.min())
print("Maximum: ",arr.max())
print("Standard deviation: ",arr.std())
print("Median: ",np.median(arr))
#

Mean:  20.0
Minimum:  12
Maximum:  30
Standard deviation:  6.027713773341708
Median:  19.0

Q4. NumPy Filtering

In [ ]:
#Using NumPy, extract all values that are greater than 40.
arr = np.array([10, 25, 30, 45, 50, 65, 70])
print("Array which the values are greater than 40: ",arr[arr>40])

Array which the values are greater than 40:  [45 50 65 70]

Q5. Create a Pandas DataFrame – 2 Marks
Create the following DataFrame using Pandas:
Name Age Score
Anu 21 85
Rahul 22 72
Meera 20 91
Arun 23 68
Display the DataFrame.

In [56]:
# Q5. Create a Pandas DataFrame – 2 Marks
#Create the following DataFrame using Pandas:
#Name Age Score
#Anu 21 85
#Rahul 22 72
#Meera 20 91
#Arun 23 68
#Display the DataFrame.

name=["Anu","Rahul","Meera","Arun"]
age=[21,22,20,23]
score=[85,72,91,68]
import pandas as pd
df=pd.DataFrame({"Name":name,"Age":age,"Score":score})
df

    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

# Q6. DataFrame Selection
Using the DataFrame created in Q5:
Display only the Name and Score columns.
Display the complete record of Meera .

In [93]:

#Using the DataFrame created in Q5:
#Display only the Name and Score columns.
#Display the complete record of Meera .
print("Name and Score columns: ",df[["Name","Score"]])
print("Complete record of Meera: ",df[df["Name"]=="Meera"])
#

Name and Score columns:      Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68
Complete record of Meera:      Name  Age  Score
2  Meera   20     91

In [94]:
#Q7. DataFrame Filtering – 2 Marks
#Using the DataFrame from Q5, display all students whose Score is greater than 75
df[df["Score"]>75]

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

In [95]:
#Q8. DataFrame Inspection – 2 Marks
#Using the DataFrame from Q5, display:
#Number of rows and columns
#Column names
#Data types
#Basic statistical summary
print("Number of rows and columns: ",df.shape)
print("Column names: ",df.columns)
print("Data types: ",df.dtypes)
print("Basic statistical summary: ",df.describe())

Number of rows and columns:  (4, 3)
Column names:  Index(['Name', 'Age', 'Score'], dtype='object')
Data types:  Name     object
Age       int64
Score     int64
dtype: object
Basic statistical summary:               Age      Score
count   4.000000   4.000000
mean   21.500000  79.000000
std     1.290994  10.801234
min    20.000000  68.000000
25%    20.750000  71.000000
50%    21.500000  78.500000
75%    22.250000  86.500000
max    23.000000  91.000000

In [ ]:
#Q9. Sorting a DataFrame – 2 Marks
#Sort the DataFrame from Q5 by Score in descending order
df.sort_values(by="Score",ascending=False)
#

In [99]:
#Q10. Handling Missing Values – 2 Marks
#Consider the following DataFrame:
#df = pd.DataFrame({
#'Name': ['A', 'B', 'C', 'D'],
#'Age': [21, np.nan, 23, 22],
#'Score': [80, 75, np.nan, 90]
#})
#Write Pandas code to:
#Identify the missing values.
#Replace the missing Age with the mean age.
#Replace the missing Score with the mean score.
print("Missing values:",df.isnull().sum())
print("___________________________________________________________________________________")
df["Age"]=df["Age"].fillna(df["Age"].mean())
print(df)
print("___________________________________________________________________________________")
df["Score"]=df["Score"].fillna(df["Score"].mean())
print(df)

Missing values: Name     0
Age      0
Score    0
dtype: int64
___________________________________________________________________________________
    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68
___________________________________________________________________________________
    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

#SECTION B – MEDIUM

Q11: use the dataset:
student_performance.csv
The dataset contains the following columns:
Student_ID
Name
Gender
Department
Age
Attendance
Python_Score
SQL_Score
Pandas_Score
NumPy_Score
Final_Score

In [2]:
import pandas as pd
st=pd.read_csv("/content/drive/MyDrive/DSAB13/Class Activity/assessement B Numpy Pandas/student_performance[1].csv")
st

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

Perform the following:
Display the first 5 records.
Display the last 5 records.
Find the number of rows and columns.
Display the column names.
Display the data types.
Generate a statistical summary of the numerical columns.

In [4]:
#Display the first 5 records.
print("First 5 records: ",st.head(5))

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9

In [ ]:
#Display the last 5 records.
st.tail(5)

In [7]:
#Find the number of rows and columns
print("Number of (rows,columns): ",st.shape)

Number of (rows,columns):  (80, 11)

In [8]:
#Display the columns name
st.columns

Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance',
       'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score',
       'Final_Score'],
      dtype='object')

In [13]:
st.dtypes

Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object

In [14]:
#Generate a statistical summary of the numerical columns.
st.describe()

,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
count,77.000000,77.000000,78.000000,80.000000,78.000000,78.000000,78.000000
mean,22.012987,81.672727,72.821795,70.445000,70.365385,68.574359,70.696154
std,2.155126,10.054204,16.722103,14.630417,15.814294,16.417242,14.053871
min,19.000000,56.300000,39.500000,38.300000,25.000000,25.000000,40.600000
25%,20.000000,75.500000,64.525000,60.650000,61.800000,57.175000,60.450000
50%,22.000000,81.100000,72.000000,69.300000,70.000000,70.700000,70.950000
75%,24.000000,86.400000,86.525000,81.150000,82.575000,80.650000,82.275000
max,25.000000,100.000000,100.000000,100.000000,100.000000,100.000000,97.000000

Q12. Filtering and Sorting
Using the student dataset:
Find students whose Final_Score is greater than 75.
Find students whose Attendance is below 75%.
Find students from the Data Science department with Final_Score greater than 80.
Sort all students by Final_Score from highest to lowest.

In [15]:
#Find students whose Final_Score is greater than 75.
st[st["Final_Score"]>75]

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0
7,STU1008,Akhil Varma,Male,Computer Science,20.0,81.1,72.1,80.4,72.9,73.5,79.2
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1
17,STU1018,Priya Nair,Male,Data Science,19.0,85.4,62.6,81.6,79.6,75.5,75.1
23,STU1024,Fathima Joseph,Female,Commerce,23.0,78.2,87.7,71.0,88.5,74.8,83.7
24,STU1025,Kiran Varma,Female,Electronics,21.0,80.7,87.5,67.1,84.5,96.1,77.3
27,STU1028,Nikhil Nair,Female,Data Science,24.0,79.3,70.3,82.0,64.4,72.8,77.1
30,STU1031,Amal Varma,Female,Computer Science,19.0,86.7,86.9,64.3,100.0,89.2,85.5
33,STU1034,Amal Das,Male,Computer Science,19.0,85.5,94.4,81.6,71.3,81.5,84.3
35,STU1036,Maya Menon,Female,Electronics,19.0,82.0,95.3,93.4,100.0,62.5,84.2
37,STU1038,Kiran Pillai,Female,Electronics,25.0,85.2,87.8,78.3,85.5,82.7,82.4
39,STU1040,Rohan Sharma,Female,Computer Science,21.0,100.0,68.9,79.8,66.1,66.4,78.5
40,STU1041,Amal Pillai,Female,Computer Science,25.0,97.7,94.3,91.0,73.1,91.2,94.5
41,STU1042,Arun Joseph,Female,Computer Science,21.0,85.9,71.2,76.1,70.8,NaN,77.9
43,STU1044,Rahul Das,Female,Computer Science,22.0,70.9,68.0,67.3,83.6,76.7,77.3
47,STU1048,Priya Kumar,Male,Data Science,25.0,64.6,80.6,67.0,71.2,80.2,77.3
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
51,STU1052,Gokul Nair,Female,Commerce,25.0,77.3,80.4,85.3,96.7,83.5,79.3
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
56,STU1057,Rohan Pillai,Female,Commerce,20.0,79.5,72.1,66.9,61.8,72.3,75.2
57,STU1058,Diya Thomas,Female,Computer Science,23.0,83.5,93.1,78.8,91.6,83.8,92.3
58,STU1059,Anu Menon,Male,Electronics,24.0,96.7,99.7,77.1,68.9,89.7,84.9
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0
64,STU1065,Rohan Sharma,Male,Computer Science,19.0,64.4,96.5,69.3,86.7,80.7,83.5
67,STU1068,Maya Das,Female,Computer Science,23.0,66.7,83.4,79.6,89.3,83.6,83.7
73,STU1074,Anu Kumar,Female,Computer Science,22.0,95.0,95.3,67.7,92.4,81.4,83.4
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

In [16]:
#Find students whose Attendance is below 75%.
st[st["Attendance"]<75]

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
9,STU1010,Gokul Pillai,Female,Computer Science,19.0,67.3,79.6,85.0,74.1,80.5,73.8
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9
15,STU1016,Nikhil Kumar,Female,Computer Science,NaN,70.3,55.9,69.3,67.1,58.4,58.2
19,STU1020,Vivek Sharma,Female,Commerce,22.0,72.1,65.8,60.9,49.8,44.8,54.6
25,STU1026,Maya Menon,Male,Electronics,20.0,68.3,91.7,64.5,83.5,73.7,69.4
36,STU1037,Nikhil Menon,Male,Electronics,22.0,74.8,69.5,60.7,64.6,81.6,69.1
42,STU1043,Sneha Varma,female,Data Science,19.0,74.4,71.8,79.1,69.8,95.9,NaN
43,STU1044,Rahul Das,Female,Computer Science,22.0,70.9,68.0,67.3,83.6,76.7,77.3
47,STU1048,Priya Kumar,Male,Data Science,25.0,64.6,80.6,67.0,71.2,80.2,77.3
50,STU1051,Gokul Menon,Male,Data Science,25.0,70.9,68.6,81.0,64.0,63.0,70.5
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9
64,STU1065,Rohan Sharma,Male,Computer Science,19.0,64.4,96.5,69.3,86.7,80.7,83.5
67,STU1068,Maya Das,Female,Computer Science,23.0,66.7,83.4,79.6,89.3,83.6,83.7
71,STU1072,Vivek Pillai,Male,Commerce,24.0,71.5,59.0,58.2,56.3,48.9,56.6

In [20]:
# Find students from the Data Science department with Final_Score greater than 80.
st[(st["Department"]=="Data Science") & (st["Final_Score"]>80)]

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9

In [21]:
#Sort all students by Final_Score from highest to lowest
st.sort_values(by="Final_Score",ascending=False)

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0
40,STU1041,Amal Pillai,Female,Computer Science,25.0,97.7,94.3,91.0,73.1,91.2,94.5
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
57,STU1058,Diya Thomas,Female,Computer Science,23.0,83.5,93.1,78.8,91.6,83.8,92.3
...,...,...,...,...,...,...,...,...,...,...,...
34,STU1035,Rahul Pillai,Female,Data Science,22.0,82.5,41.4,44.4,53.8,43.2,44.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
26,STU1027,Aditya Pillai,Female,Computer Science,25.0,79.6,44.0,52.5,25.0,25.0,40.6
42,STU1043,Sneha Varma,female,Data Science,19.0,74.4,71.8,79.1,69.8,95.9,NaN
53,STU1054,Maya Sharma,Male,Data Science,19.0,82.5,59.7,60.5,65.8,73.3,NaN

Q13. Feature Creation
Create a new column called:
Average_Technical_Score
Calculate it using:
Python_Score
SQL_Score
Pandas_Score
NumPy_Score
Then create another column called:
Performance
using these rules:
Average Technical Score Performance>= 90 Excellent
>= 75 Good
>= 60 Average
< 60 Needs Improvement
Display the resulting DataFrame

In [33]:
import numpy as np
import pandas as pd
st["Average_Technical_Score"]=(st["Python_Score"]+st["SQL_Score"]+st["Pandas_Score"]+st["NumPy_Score"])/4
st ["Performance"]=np.where(st["Average_Technical_Score"]>=90,"Excellent",np.where(st["Average_Technical_Score"]>=75,"Good",np.where(st["Average_Technical_Score"]>=60,"Average","Needs Improvement")))
st

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7,83.575,Good
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3,65.200,Average
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1,73.400,Average
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2,54.475,Needs Improvement
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9,83.275,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2,47.775,Needs Improvement
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5,46.525,Needs Improvement
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2,80.250,Good
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4,61.350,Average
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6,77.075,Good

Q14. GroupBy Analysis – 6 Marks
Using the student dataset, calculate the following for each department:
Number of students
Average Final Score
Maximum Final Score
Minimum Final Score
Sort the resulting DataFrame by Average Final Score in descending order

In [37]:
st.groupby("Department")["Final_Score"].count()

Department
 Data Science        1
Commerce             8
Computer Science    29
Computer science     1
Data Science        25
Electronics         13
data science         1
Name: Final_Score, dtype: int64

In [39]:
st.groupby("Department")["Final_Score"].mean()

Department
 Data Science       55.100000
Commerce            67.825000
Computer Science    71.479310
Computer science    46.700000
Data Science        71.324000
Electronics         72.846154
data science        66.900000
Name: Final_Score, dtype: float64

In [40]:
# Maximum Final Score
st.groupby("Department")["Final_Score"].max()

Department
 Data Science       55.1
Commerce            83.7
Computer Science    96.0
Computer science    46.7
Data Science        97.0
Electronics         86.9
data science        66.9
Name: Final_Score, dtype: float64

In [42]:
# Minimum Final Score
st.groupby("Department")["Final_Score"].min()

Department
 Data Science       55.1
Commerce            54.6
Computer Science    40.6
Computer science    46.7
Data Science        43.5
Electronics         51.2
data science        66.9
Name: Final_Score, dtype: float64

Q15. NumPy and Pandas Integration
Using the student dataset:
Convert the Final_Score column into a NumPy array.
Calculate using NumPy:
Mean
Median
Standard deviation
25th percentile
75th percentile
Identify all students whose Final_Score is above the overall mean.

In [35]:
#Convert the Final_Score column into a NumPy array
import numpy as np
import pandas as pd
st["Final_Score"].to_numpy()

array([82.7, 60.3, 67.1, 57.2, 81.9, 55.1, 77. , 79.2, 83. , 73.8, 91.9,
       86.9, 50.8, 69.9, 47.1, 58.2, 91.1, 75.1, 66.9, 54.6, 73.2, 55.5,
       64.6, 83.7, 77.3, 69.4, 40.6, 77.1, 62.1, 59.1, 85.5, 46.7, 70.6,
       84.3, 44.2, 84.2, 69.1, 82.4, 62.2, 78.5, 94.5, 77.9,  nan, 77.3,
       64.6, 70.5, 74.8, 77.3, 97. , 59.1, 70.5, 79.3, 71. ,  nan, 66. ,
       93.3, 75.2, 92.3, 84.9, 87.9, 70.8, 96. , 60.9, 45.6, 83.5, 61.1,
       70.7, 83.7, 52.9, 52.1, 51.2, 56.6, 73.5, 83.4, 70.9, 47.2, 43.5,
       75.2, 63.4, 78.6])

In [62]:
#Calculate using NumPy

print("Mean: ",np.mean(st["Final_Score"]))
print("Median: ",np.median(st["Final_Score"]))
print("Standard deviation: ",np.std(st["Final_Score"]))
print("25th percentile: ",np.percentile(st["Final_Score"],25))
print("75th percentile: ",np.percentile(st["Final_Score"],75))
print(st.groupby("Department")["Final_Score"].mean())
print("Overall mean: ",np.mean(st["Final_Score"]))
print("all students whose Final_Score is above the overall mean: ",st["Final_Score"]>np.mean(st["Final_Score"]))

Mean:  70.69615384615385
Median:  nan
Standard deviation:  13.963491245788179
25th percentile:  nan
75th percentile:  nan
Department
 Data Science       55.100000
Commerce            67.825000
Computer Science    71.479310
Computer science    46.700000
Data Science        71.324000
Electronics         72.846154
data science        66.900000
Name: Final_Score, dtype: float64
Overall mean:  70.69615384615385
all students whose Final_Score is above the overall mean:  0      True
1     False
2     False
3     False
4      True
      ...
75    False
76    False
77     True
78    False
79     True
Name: Final_Score, Length: 80, dtype: bool

# SECTION C – HARD

A. Data Cleaning
Identify missing values.
Handle missing numerical values appropriately.

In [63]:
st.isnull().sum()

Student_ID                 0
Name                       0
Gender                     0
Department                 0
Age                        3
Attendance                 3
Python_Score               2
SQL_Score                  0
Pandas_Score               2
NumPy_Score                2
Final_Score                2
Average_Technical_Score    6
Performance                0
dtype: int64

 Feature Engineering
Create a column:
Average_Score
using the Python, SQL, Pandas and NumPy scores.
Create another column:
Pass_Status
using:
Average_Score >= 50 → Pass
Average_Score < 50 → Fail

In [65]:
st["Average_Score"]=(st["Python_Score"]+st["SQL_Score"]+st["Pandas_Score"]+st["NumPy_Score"])/4
st["Pass_Status"]=np.where(st["Average_Score"]>=50,"Pass","Fail")
st

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance,Average_Score,Pass_Status
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7,83.575,Good,83.575,Pass
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3,65.200,Average,65.200,Pass
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1,73.400,Average,73.400,Pass
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2,54.475,Needs Improvement,54.475,Pass
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9,83.275,Good,83.275,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2,47.775,Needs Improvement,47.775,Fail
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5,46.525,Needs Improvement,46.525,Fail
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2,80.250,Good,80.250,Pass
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4,61.350,Average,61.350,Pass
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6,77.075,Good,77.075,Pass

C. Analysis
Find:
Top 5 students based on Average_Score .
Department having the highest average score.
Average attendance by department.
Number of students who passed and failed.

In [66]:
st.sort_values(by="Average_Score",ascending=False).head(5)

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance,Average_Score,Pass_Status
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9,95.625,Excellent,95.625,Pass
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0,95.200,Excellent,95.200,Pass
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0,92.125,Excellent,92.125,Pass
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1,89.350,Good,89.350,Pass
35,STU1036,Maya Menon,Female,Electronics,19.0,82.0,95.3,93.4,100.0,62.5,84.2,87.800,Good,87.800,Pass

In [68]:
#Department having the highest average score.
st.groupby("Department")["Average_Score"].mean().sort_values(ascending=False).head(1)

Department
Electronics    74.063462
Name: Average_Score, dtype: float64

In [69]:
st.groupby("Department")["Attendance"].mean()

Department
 Data Science       76.700000
Commerce            77.437500
Computer Science    82.807143
Computer science    92.100000
Data Science        82.092308
Electronics         80.576923
data science              NaN
Name: Attendance, dtype: float64

In [70]:
st.groupby("Pass_Status")["Pass_Status"].count()

Pass_Status
Fail    14
Pass    66
Name: Pass_Status, dtype: int64

. Summary
Create a summary DataFrame containing:
Department
Total_Students
Average_Score
Average_Attendance
Pass_Count
Fail_Count

In [77]:
#Create a summary DataFrame containing:
#Department
print(st.groupby("Department")["Department"].count())
print("___________________________________________________________________________________")
#Total_Students
print(st.groupby("Department")["Name"].count())
print("___________________________________________________________________________________")
#Average_Score
print(st.groupby("Department")["Average_Score"].mean())
print("___________________________________________________________________________________")
#Average_Attendance
print(st.groupby("Department")["Attendance"].mean())
print("___________________________________________________________________________________")
#Pass_Count Fail Count
print(st.groupby("Pass_Status")["Pass_Status"].count())
print("___________________________________________________________________________________")

Department
 Data Science        1
Commerce             8
Computer Science    29
Computer science     1
Data Science        27
Electronics         13
data science         1
Name: Department, dtype: int64
___________________________________________________________________________________
Department
 Data Science        1
Commerce             8
Computer Science    29
Computer science     1
Data Science        27
Electronics         13
data science         1
Name: Name, dtype: int64
___________________________________________________________________________________
Department
 Data Science       59.200000
Commerce            68.278571
Computer Science    70.474107
Computer science          NaN
Data Science        70.725000
Electronics         74.063462
data science        64.725000
Name: Average_Score, dtype: float64
___________________________________________________________________________________
Department
 Data Science       76.700000
Commerce            77.437500
Computer Science    82.807143
Computer science    92.100000
Data Science        82.092308
Electronics         80.576923
data science              NaN
Name: Attendance, dtype: float64
___________________________________________________________________________________
Pass_Status
Fail    14
Pass    66
Name: Pass_Status, dtype: int64
___________________________________________________________________________________

#Q18. Advanced NumPy and Pandas Analysis

In [116]:
import numpy as np
import pandas as pd
em=pd.read_csv("/content/drive/MyDrive/DSAB13/Class Activity/assessement B Numpy Pandas/employee[1].csv")
em

,Employee_ID,Department,Experience,Salary,Performance_Score,Projects_Completed
0,EMP2001,HR,NaN,76776.0,57.7,6.0
1,EMP2002,Software Development,8.7,78243.0,85.6,11.0
2,EMP2003,Data Analytics,3.1,52854.0,77.5,6.0
3,EMP2004,Data Analytics,6.9,65088.0,78.5,8.0
4,EMP2005,data analytics,3.4,46324.0,73.8,6.0
...,...,...,...,...,...,...
70,EMP2071,NaN,3.0,67088.0,77.6,5.0
71,EMP2072,Software Development,3.3,44689.0,69.4,8.0
72,EMP2073,Data Engineering,8.3,83685.0,87.4,16.0
73,EMP2074,Data Engineering,6.9,84323.0,63.5,12.0
74,EMP2075,Software Development,10.1,98224.0,83.6,13.0

In [117]:
em.head()

,Employee_ID,Department,Experience,Salary,Performance_Score,Projects_Completed
0,EMP2001,HR,NaN,76776.0,57.7,6.0
1,EMP2002,Software Development,8.7,78243.0,85.6,11.0
2,EMP2003,Data Analytics,3.1,52854.0,77.5,6.0
3,EMP2004,Data Analytics,6.9,65088.0,78.5,8.0
4,EMP2005,data analytics,3.4,46324.0,73.8,6.0

In [118]:
em.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         75 non-null     object
 1   Department          74 non-null     object
 2   Experience          73 non-null     object
 3   Salary              72 non-null     object
 4   Performance_Score   73 non-null     float64
 5   Projects_Completed  73 non-null     float64
dtypes: float64(2), object(4)
memory usage: 3.6+ KB

. NumPy Analysis
Convert Salary and Performance_Score into NumPy arrays.
Calculate:
Mean salary
Median salary
Standard deviation of salary
Mean performance score

In [119]:
import numpy as np
em["Salary"].to_numpy()

array(['76776.0', '78243.0', '52854.0', '65088.0', '46324.0', '62749.0',
       '51328.0', '70881.0', '52657.0', '23083.0', '46271.0', '44922.0',
       '68546.0', '67786.0', '56120.0', nan, '52311.0', '79595.0',
       '45369.0', '41282.0', '69207.0', '24036.0', '83674.0', '109642.0',
       '56354.0', '45336.0', '74816.0', '68128.0', '65579.0', '78,500',
       '60930.0', '65566.0', '55155.0', '50517.0', '52721.0', '56838.0',
       '73192.0', '22000.0', nan, '33927.0', '50019.0', '96565.0',
       '82170.0', '66053.0', nan, '51056.0', '61704.0', '66074.0',
       '43341.0', '68620.0', '60594.0', '36947.0', '64357.0', '62522.0',
       '22000.0', '63338.0', '48179.0', '68152.0', '52079.0', '99744.0',
       '83576.0', '43990.0', '74892.0', '28473.0', '61142.0', '82567.0',
       '61196.0', '73254.0', '56288.0', '60755.0', '67088.0', '44689.0',
       '83685.0', '84323.0', '98224.0'], dtype=object)

In [120]:
import numpy as np
em["Performance_Score"].to_numpy()

array([57.7, 85.6, 77.5, 78.5, 73.8, 72.2, 91. , 67.9, 64.1, 66. , 77.2,
       53.2, 51.6, 51.7, 71.9, 73.4, 61.3, 83. , 60.2, 74.1, 71.1, 74. ,
       81. , 76. , 69.5, 88. , 84.3, 56.3, 78.8, 52.9, 94.4, 85.7, 72.1,
       76.6, 68.3, 79.3, 72.8, 69.6,  nan, 59.7, 63. , 70.1, 67.3, 52.6,
       77.7, 92.8,  nan, 54.7, 82.2, 90.9, 67.4, 67.5, 47.2, 82.1, 53.9,
       75.3, 50.8, 81.1, 84.1, 72.5, 63.1, 41.1, 88. , 62.9, 52.3, 81.1,
       65.9, 66. , 63.2, 83.4, 77.6, 69.4, 87.4, 63.5, 83.6])

#Filtering
Find employees satisfying both conditions:
Experience > 3 years
AND
Performance_Score >= 80

In [121]:
#Find employees satisfying both conditions: Experience > 3 years AND Performance_Score >= 80
em[(em["Experience"]>3) & (em["Performance_Score"]>=80)]
#

TypeError: '>' not supported between instances of 'str' and 'int'